version: '3.8'
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "testcase"
      POSTGRES_PASSWORD: "QtSItP3oCgWSLWt81o2r"
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    container_name: testcase_pgdb
    restart: always
  syncshare-accounts:
    build: /
    environment:
      # ==== Django settings ====
      DJANGO_DEBUG: "false"
      DJANGO_SECRET_KEY: "INSECURE"
      DJANGO_ALLOWED_HOSTS: '["127.0.0.1", "localhost"]'
      # ==== Database settings ====
      DATABASE_ENGINE: "postgres"
      DATABASE_HOST: "localhost.com"
      DATABASE_NAME: "testcase"
      DATABASE_USER: "testcase"
      DATABASE_USER_PASSWORD: "INSECURE"
      DATABASE_PORT: 5432
    ports:
      - "8002:8002"
    depends_on:
      - postgres


volumes:
  postgres: