# Generated by Django 5.0.4 on 2024-04-05 02:13

import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import types
import typing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zipCode', models.CharField(max_length=6, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('apartment', models.CharField(max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=6)),
                ('giver', models.CharField(max_length=100)),
                ('dateIssued', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('surname', models.CharField(max_length=20, null=True)),
                ('patronymic', models.CharField(max_length=20, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('documentIds', django_pydantic_field.fields.PydanticSchemaField(config=None, default=[], encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=django_pydantic_field.compat.django.GenericContainer(typing.Union, (django_pydantic_field.compat.django.GenericContainer(list, (uuid.UUID,)), types.NoneType)))),
                ('curWorkExp', models.SmallIntegerField(null=True)),
                ('typeEducation', models.SmallIntegerField(choices=[('secondary', 'Среднее'), ('secondarySpecial', 'Среднее специальное'), ('incompleteHigher', 'Незаконченное высшее'), ('higher', 'Высшее'), ('twoOrMoreHigher', 'Два и более высших образований'), ('academicDegree', 'Академическая степень')])),
                ('monIncome', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('monExpenses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('livingAddress', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_living_address', to='api.address')),
                ('regAddress', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_reg_address', to='api.address')),
                ('spouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
                ('passport', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.passport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('surname', models.CharField(max_length=20, null=True)),
                ('patronymic', models.CharField(max_length=20, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[('email', 'Электронная почта'), ('phone', 'Мобильный телефон')])),
                ('value', models.CharField(max_length=256)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[('main', 'Основная работа'), ('part-time', 'Частичная занятость')], null=True)),
                ('dateEmp', models.DateTimeField(null=True)),
                ('dateDismissal', models.DateTimeField(null=True)),
                ('monIncome', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tin', models.CharField(max_length=15, null=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('factAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_fact_address', to='api.address')),
                ('jurAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_jur_address', to='api.address')),
            ],
        ),
    ]
