# Generated by Django 5.0.4 on 2024-04-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='typeEducation',
            field=models.CharField(choices=[('secondary', 'Среднее'), ('secondarySpecial', 'Среднее специальное'), ('incompleteHigher', 'Незаконченное высшее'), ('higher', 'Высшее'), ('twoOrMoreHigher', 'Два и более высших образований'), ('academicDegree', 'Академическая степень')], max_length=20),
        ),
        migrations.AlterField(
            model_name='communication',
            name='type',
            field=models.CharField(choices=[('email', 'Электронная почта'), ('phone', 'Мобильный телефон')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('main', 'Основная работа'), ('part-time', 'Частичная занятость')], max_length=10, null=True),
        ),
    ]
