# Generated by Django 5.0.4 on 2024-04-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_typeeducation_alter_communication_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='factAddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_fact_address', to='api.address'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jurAddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_jur_address', to='api.address'),
        ),
    ]
